AWSTemplateFormatVersion: "2010-09-09"
Description: Automate provisioning of CodeBuild
Parameters:
  EmailAddress:
    Type: String
    Default: st120367@ait.asia
  DBUrl:
    Type: String
    Default: '35.197.150.136'
  DBPassword:
    Type: String
  DBPort:
    Type: String
    Default: 5432
  MasterKey:
    Type: String
Resources:
  CodeBuildSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: meal-agent-codebuild-notification
      Subscription:
        - Endpoint: st120367@ait.asia
          Protocol: email-json
  CodeBuildNotification:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule"
      EventPattern:
        source:
          - "aws.codebuild"
        detail-type:
          - "CodeBuild Build State Change"
        detail:
          build-status:
            - "SUCCEEDED"
            - "FAILED"
      State: "ENABLED"
      Targets:
      -
        Arn:
          Ref: "CodeBuildSNS"
        Id: "OpsTopic"
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  MealAgentCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      BadgeEnabled: true
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Location: https://github.com/kanniep/meal-agent.git
        Type: "GITHUB"
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - cd rails-api
                - bundle install
            pre_build:
              commands:
                - RAILS_ENV=test bundle exec rake db:migrate
                - bundle exec rspec
                - bundle exec cucumber --format html --out coverage/cucumber.html
                - bundle exec rake metrics:all
            build:
              commands:
                - cp -r tmp/metric_fu public/
                - cp -r coverage public/
                - echo ${MASTER_KEY} > config/master.key
                - $(aws ecr get-login --no-include-email)
                - docker build -t "917443201129.dkr.ecr.ap-southeast-1.amazonaws.com/meal-agent-rails:${CODEBUILD_BUILD_ID}" --build-arg database_url=${DATABASE_URL} --build-arg database_password=${DATABASE_PASSWORD} --build-arg database_port=${DATABASE_PORT} .
                - docker push 917443201129.dkr.ecr.ap-southeast-1.amazonaws.com/meal-agent-rails:${CODEBUILD_BUILD_ID}
            post_build:
              commands:
                - cd ../iac/
                - aws cloudformation deploy --template-file ecs-template.yaml --stack-name ECS-MealAgent --parameter-overrides VpcId=vpc-dd3a1cba KeyName=kantapon-aws SubnetId=subnet-689c970f,subnet-1e261d57 DBUrl=${DATABASE_URL} DBPassword=${DATABASE_PASSWORD} --ImageTag=${CODEBUILD_BUILD_ID} --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/ruby:2.5.1"
        Type: "LINUX_CONTAINER"
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: DATABASE_URL
            Type: PLAINTEXT
            Value: !Ref DBUrl
          - Name: DATABASE_PASSWORD
            Type: PLAINTEXT
            Value: !Ref DBPassword
          - Name: DATABASE_PORT
            Type: PLAINTEXT
            Value: !Ref DBPort
          - Name: DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL
            Type: PLAINTEXT
            Value: true
          - Name: MASTER_KEY
            Type: PLAINTEXT
            Value: !Ref MasterKey
      Name: !Sub ${AWS::StackName}-meal-agent-ci
      Description: rspec, cucumber and metric_fu
      ServiceRole: !Ref CodeBuildRole
      TimeoutInMinutes: 60
