default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= "postgres://postgres:#{ENV['DATABASE_PASSWORD']}@#{ENV['DATABASE_URL']}:#{ENV['DATABASE_PORT']}/meal-agent_development" %>

test: &test
  <<: *default
  url: <%= "postgres://postgres:#{ENV['DATABASE_PASSWORD']}@#{ENV['DATABASE_URL']}:#{ENV['DATABASE_PORT']}/meal-agent_test" %>

production:
  <<: *default
  url: <%= "postgres://postgres:#{ENV['DATABASE_PASSWORD']}@#{ENV['DATABASE_URL']}:#{ENV['DATABASE_PORT']}/meal-agent_production" %>

cucumber:
  <<: *test
